/*
  The FINAL Reconnect taxonomy (from the product's category PDF).

  Three levels, exactly as the rest of the platform models them:
    audience  → who you're reconnecting with  (the 8 "Reconnect with …")
    category  → the 10 broad themes            (Wellness & Healing, …)
    type      → the individual experience      (Yoga Retreats, …)

  Below is the raw [audience, category, type] list transcribed from the PDF
  (case normalised — the sheet had a stray "Arts & creativity"). seedTaxonomyV2
  derives the audiences, the categories (tagged with every audience they appear
  under) and the per-category types from it, de-duplicating as it goes.
*/

// The 8 audiences, in display order.
const AUDIENCES = [
  'Yourself', 'Partner', 'Kids', 'Parents', 'Family', 'Friends', 'Community', 'Teams',
];

// The 10 broad categories, in display order.
const CATEGORIES = [
  'Wellness & Healing',
  'Learning & Personal Growth',
  'Arts & Creativity',
  'Adventure & Exploration',
  'Sports and Fun',
  'Food & Culture',
  'Spiritual & Heritage',
  'Relationships & Community',
  'Group Experiences',
  'Corporate Experiences',
];

// [audience, category, type] — the PDF, row for row.
const TRIPLES = [
  // ── Yourself ──────────────────────────────────────────────────────────
  ['Yourself', 'Wellness & Healing', 'Yoga Retreats'],
  ['Yourself', 'Wellness & Healing', 'Meditation Retreats'],
  ['Yourself', 'Wellness & Healing', 'Silent Retreats'],
  ['Yourself', 'Wellness & Healing', 'Ayurveda Retreats'],
  ['Yourself', 'Wellness & Healing', 'Detox Retreats'],
  ['Yourself', 'Wellness & Healing', 'Panchakarma Programs'],
  ['Yourself', 'Wellness & Healing', 'Sound Healing'],
  ['Yourself', 'Wellness & Healing', 'Reiki Healing'],
  ['Yourself', 'Wellness & Healing', 'Breathwork Sessions'],
  ['Yourself', 'Wellness & Healing', 'Energy Healing'],
  ['Yourself', 'Wellness & Healing', 'Spa Retreats'],
  ['Yourself', 'Wellness & Healing', 'Wellness Weekends'],
  ['Yourself', 'Learning & Personal Growth', 'Life Coaching'],
  ['Yourself', 'Corporate Experiences', 'Executive Coaching'],
  ['Yourself', 'Learning & Personal Growth', 'Mindfulness Workshops'],
  ['Yourself', 'Learning & Personal Growth', 'Emotional Intelligence Workshops'],
  ['Yourself', 'Learning & Personal Growth', 'Confidence Building Workshops'],
  ['Yourself', 'Corporate Experiences', 'Leadership Retreats'],
  ['Yourself', 'Learning & Personal Growth', 'Journaling Workshops'],
  ['Yourself', 'Learning & Personal Growth', 'Vision Board Workshops'],
  ['Yourself', 'Learning & Personal Growth', 'Goal Setting Retreats'],
  ['Yourself', 'Arts & Creativity', 'Pottery Workshops'],
  ['Yourself', 'Arts & Creativity', 'Painting Workshops'],
  ['Yourself', 'Wellness & Healing', 'Art Therapy'],
  ['Yourself', 'Arts & Creativity', 'Photography Workshops'],
  ['Yourself', 'Arts & Creativity', 'Music Workshops'],
  ['Yourself', 'Arts & Creativity', 'Dance Workshops'],
  ['Yourself', 'Learning & Personal Growth', 'Creative Writing Retreats'],
  ['Yourself', 'Arts & Creativity', 'Creative Writing Retreats'],
  ['Yourself', 'Arts & Creativity', 'Floral Arrangement Workshops'],
  ['Yourself', 'Adventure & Exploration', 'Hiking Retreats'],
  ['Yourself', 'Adventure & Exploration', 'Cycling Tours'],
  ['Yourself', 'Sports and Fun', 'Fitness Bootcamps'],
  ['Yourself', 'Sports and Fun', 'Marathon Camps'],
  ['Yourself', 'Sports and Fun', 'Swimming Clinics'],
  ['Yourself', 'Sports and Fun', 'Martial Arts Workshops'],

  // ── Partner ───────────────────────────────────────────────────────────
  ['Partner', 'Wellness & Healing', 'Couple Retreats'],
  ['Partner', 'Relationships & Community', 'Couple Retreats'],
  ['Partner', 'Group Experiences', 'Luxury Staycations'],
  ['Partner', 'Group Experiences', 'Glamping'],
  ['Partner', 'Group Experiences', 'Sunset Cruises'],
  ['Partner', 'Food & Culture', 'Candlelight Dinners'],
  ['Partner', 'Food & Culture', 'Private Dining'],
  ['Partner', 'Group Experiences', 'Stargazing'],
  ['Partner', 'Adventure & Exploration', 'Hot Air Balloon Rides'],
  ['Partner', 'Wellness & Healing', 'Couple Yoga'],
  ['Partner', 'Wellness & Healing', 'Couple Meditation'],
  ['Partner', 'Wellness & Healing', 'Couple Spa'],
  ['Partner', 'Wellness & Healing', 'Couple Sound Healing'],
  ['Partner', 'Relationships & Community', 'Relationship Retreats'],
  ['Partner', 'Adventure & Exploration', 'Scuba Diving'],
  ['Partner', 'Adventure & Exploration', 'Trekking'],
  ['Partner', 'Adventure & Exploration', 'Kayaking'],
  ['Partner', 'Adventure & Exploration', 'Sailing'],
  ['Partner', 'Adventure & Exploration', 'Road Trips'],
  ['Partner', 'Adventure & Exploration', 'Camping'],
  ['Partner', 'Food & Culture', 'Cooking Classes'],
  ['Partner', 'Arts & Creativity', 'Dance Classes'],
  ['Partner', 'Food & Culture', 'Wine Appreciation'],
  ['Partner', 'Arts & Creativity', 'Pottery Workshops'],
  ['Partner', 'Arts & Creativity', 'Art Workshops'],

  // ── Kids ──────────────────────────────────────────────────────────────
  ['Kids', 'Learning & Personal Growth', 'Science Workshops'],
  ['Kids', 'Learning & Personal Growth', 'Robotics Classes'],
  ['Kids', 'Learning & Personal Growth', 'Coding Classes'],
  ['Kids', 'Learning & Personal Growth', 'STEM Camps'],
  ['Kids', 'Learning & Personal Growth', 'Astronomy Experiences'],
  ['Kids', 'Learning & Personal Growth', 'Museum Visits'],
  ['Kids', 'Learning & Personal Growth', 'Educational Tours'],
  ['Kids', 'Arts & Creativity', 'Art Workshops'],
  ['Kids', 'Arts & Creativity', 'Craft Workshops'],
  ['Kids', 'Arts & Creativity', 'Pottery Classes'],
  ['Kids', 'Arts & Creativity', 'Music Classes'],
  ['Kids', 'Arts & Creativity', 'Dance Classes'],
  ['Kids', 'Arts & Creativity', 'Theatre Workshops'],
  ['Kids', 'Learning & Personal Growth', 'Storytelling Sessions'],
  ['Kids', 'Sports and Fun', 'Theme Parks'],
  ['Kids', 'Sports and Fun', 'Water Parks'],
  ['Kids', 'Sports and Fun', 'Trampoline Parks'],
  ['Kids', 'Sports and Fun', 'Indoor Play Zones'],
  ['Kids', 'Sports and Fun', 'Adventure Parks'],
  ['Kids', 'Adventure & Exploration', 'Zipline Experiences'],
  ['Kids', 'Adventure & Exploration', 'Camping'],
  ['Kids', 'Group Experiences', 'Farm Visits'],
  ['Kids', 'Adventure & Exploration', 'Nature Trails'],
  ['Kids', 'Adventure & Exploration', 'Wildlife Safaris'],
  ['Kids', 'Adventure & Exploration', 'Bird Watching'],
  ['Kids', 'Food & Culture', 'Cooking Together'],
  ['Kids', 'Food & Culture', 'Baking Workshops'],
  ['Kids', 'Sports and Fun', 'Treasure Hunts'],
  ['Kids', 'Arts & Creativity', 'DIY Workshops'],
  ['Kids', 'Arts & Creativity', 'Family Photoshoots'],

  // ── Parents ───────────────────────────────────────────────────────────
  ['Parents', 'Wellness & Healing', 'Senior Wellness Retreats'],
  ['Parents', 'Wellness & Healing', 'Ayurveda Retreats'],
  ['Parents', 'Wellness & Healing', 'Spa Retreats'],
  ['Parents', 'Wellness & Healing', 'Yoga Programs'],
  ['Parents', 'Wellness & Healing', 'Nature Retreats'],
  ['Parents', 'Spiritual & Heritage', 'Heritage Walks'],
  ['Parents', 'Spiritual & Heritage', 'Museum Tours'],
  ['Parents', 'Spiritual & Heritage', 'Cultural Festivals'],
  ['Parents', 'Arts & Creativity', 'Classical Music Concerts'],
  ['Parents', 'Spiritual & Heritage', 'Local Cultural Experiences'],
  ['Parents', 'Spiritual & Heritage', 'Pilgrimages'],
  ['Parents', 'Wellness & Healing', 'Ashram Retreats'],
  ['Parents', 'Wellness & Healing', 'Spiritual Retreats'],
  ['Parents', 'Food & Culture', 'Temple Tours'],
  ['Parents', 'Wellness & Healing', 'Meditation Retreats'],
  ['Parents', 'Adventure & Exploration', 'Luxury Train Journeys'],
  ['Parents', 'Adventure & Exploration', 'River Cruises'],
  ['Parents', 'Adventure & Exploration', 'Scenic Rail Trips'],
  ['Parents', 'Adventure & Exploration', 'Tea Estate Stays'],
  ['Parents', 'Adventure & Exploration', 'Houseboat Experiences'],
  ['Parents', 'Adventure & Exploration', 'Slow Travel Holidays'],
  ['Parents', 'Learning & Personal Growth', 'Gardening Workshops'],
  ['Parents', 'Food & Culture', 'Cooking Workshops'],
  ['Parents', 'Arts & Creativity', 'Art Workshops'],
  ['Parents', 'Arts & Creativity', 'Music Workshops'],

  // ── Family ────────────────────────────────────────────────────────────
  ['Family', 'Adventure & Exploration', 'Family Staycations'],
  ['Family', 'Adventure & Exploration', 'Family Vacations'],
  ['Family', 'Adventure & Exploration', 'Family Retreats'],
  ['Family', 'Adventure & Exploration', 'Multi-Generational Travel'],
  ['Family', 'Food & Culture', 'Cooking Workshops'],
  ['Family', 'Arts & Creativity', 'Art Workshops'],
  ['Family', 'Food & Culture', 'Cultural Workshops'],
  ['Family', 'Learning & Personal Growth', 'Gardening Workshops'],
  ['Family', 'Adventure & Exploration', 'Camping'],
  ['Family', 'Adventure & Exploration', 'Trekking'],
  ['Family', 'Adventure & Exploration', 'Wildlife Safaris'],
  ['Family', 'Sports and Fun', 'Adventure Parks'],
  ['Family', 'Sports and Fun', 'Theme Parks'],
  ['Family', 'Sports and Fun', 'Water Parks'],
  ['Family', 'Learning & Personal Growth', 'Interactive Museums'],
  ['Family', 'Food & Culture', 'Festivals'],
  ['Family', 'Arts & Creativity', 'Live Shows'],

  // ── Friends ───────────────────────────────────────────────────────────
  ['Friends', 'Sports and Fun', 'Escape Rooms'],
  ['Friends', 'Sports and Fun', 'Karaoke Nights'],
  ['Friends', 'Sports and Fun', 'Board Game Cafes'],
  ['Friends', 'Sports and Fun', 'Trivia Nights'],
  ['Friends', 'Sports and Fun', 'Comedy Shows'],
  ['Friends', 'Adventure & Exploration', 'Trekking'],
  ['Friends', 'Adventure & Exploration', 'Camping'],
  ['Friends', 'Sports and Fun', 'Rafting'],
  ['Friends', 'Sports and Fun', 'Ziplining'],
  ['Friends', 'Sports and Fun', 'Rock Climbing'],
  ['Friends', 'Sports and Fun', 'ATV Experiences'],
  ['Friends', 'Food & Culture', 'Food Trails'],
  ['Friends', 'Food & Culture', 'Brewery Tours'],
  ['Friends', 'Food & Culture', 'Wine Tastings'],
  ['Friends', 'Food & Culture', 'Rooftop Experiences'],
  ['Friends', 'Food & Culture', 'Brunch Experiences'],
  ['Friends', 'Adventure & Exploration', 'Weekend Getaways'],
  ['Friends', 'Adventure & Exploration', 'Backpacking Trips'],
  ['Friends', 'Adventure & Exploration', 'Road Trips'],
  ['Friends', 'Adventure & Exploration', 'Group Retreats'],

  // ── Community ─────────────────────────────────────────────────────────
  ['Community', 'Relationships & Community', 'NGO Volunteering'],
  ['Community', 'Relationships & Community', 'Animal Shelter Programs'],
  ['Community', 'Relationships & Community', 'Rural Tourism'],
  ['Community', 'Relationships & Community', 'Community Projects'],
  ['Community', 'Relationships & Community', 'Sustainability Programs'],
  ['Community', 'Relationships & Community', 'Tree Plantation Drives'],
  ['Community', 'Relationships & Community', 'Beach Cleanups'],
  ['Community', 'Relationships & Community', 'Environmental Campaigns'],
  ['Community', 'Food & Culture', 'Local Festivals'],
  ['Community', 'Food & Culture', 'Cultural Gatherings'],
  ['Community', 'Food & Culture', 'Community Markets'],
  ['Community', 'Relationships & Community', 'Neighbourhood Events'],
  ['Community', 'Corporate Experiences', 'Startup Meetups'],
  ['Community', 'Corporate Experiences', 'Entrepreneur Circles'],
  ['Community', 'Corporate Experiences', 'Industry Networking Events'],

  // ── Teams ─────────────────────────────────────────────────────────────
  ['Teams', 'Corporate Experiences', 'Outdoor Team Challenges'],
  ['Teams', 'Corporate Experiences', 'Adventure Team Activities'],
  ['Teams', 'Corporate Experiences', 'Corporate Retreats'],
  ['Teams', 'Corporate Experiences', 'Offsites'],
  ['Teams', 'Wellness & Healing', 'Corporate Wellness Retreats'],
  ['Teams', 'Wellness & Healing', 'Stress Management Workshops'],
  ['Teams', 'Wellness & Healing', 'Mindfulness Sessions'],
  ['Teams', 'Wellness & Healing', 'Yoga Programs'],
  ['Teams', 'Corporate Experiences', 'Leadership Retreats'],
  ['Teams', 'Corporate Experiences', 'Innovation Workshops'],
  ['Teams', 'Corporate Experiences', 'Strategy Offsites'],
  ['Teams', 'Corporate Experiences', 'Skill Development Programs'],
  ['Teams', 'Corporate Experiences', 'Team Outings'],
  ['Teams', 'Corporate Experiences', 'Annual Celebrations'],
  ['Teams', 'Corporate Experiences', 'Reward Trips'],
  ['Teams', 'Corporate Experiences', 'Employee Appreciation Events'],
];

module.exports = { AUDIENCES, CATEGORIES, TRIPLES };
